% JSS - Folder for code related to JSS article.
% NB most of these m-files are not well documented.
% 
% jsstutorial - this replicates the commands and figures used in the tutorial 
%               section of the paper. The MATLAB command 'echodemo jsstutorial' 
%               is the recommended way of running this m-file.
%
% jssfigures  - this generates the figures in the paper. These are the same
%               as those generated by jsstutorial, but slightly formatted.
%
% jsstable/table_entry - used to generate data for table 1. Note that you must 
%               have R installed on your system to get comparative timings.
%
%
% As well as the above, there are a few additional demo files:
%
% penaltydemo1 - generates some data and fits a gaussian model with nine
%                different penalties.
%
% penaltydemo2 - generates some data and cross-validates a gaussian model
%                with six different penalties
%
% genmodel - creates random data for the above m-files
% panels   - changes sizes of axes in matlab plots